apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: spring-boot-skaffold
build:
  artifacts:
    - image: springboot-skaffold
      jib:
        project: id.my.hendisantika:skaffold
manifests:
  rawYaml:
    - k8s/deployment.yml
    - k8s/service.yml
