apiVersion: v1
kind: Service
metadata:
  name: springboot-skaffold-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-skaffold
